language: java
jdk:
- openjdk8

addons:
sonarcloud:
organization: "sonarcloud"
token:
secure: "82a814249a14a270497f5033064b061a87cd3831"

script:
- ant build
- sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
